export const FETCH_ONLINE_VISITORS_REQUESTED = Symbol('visitors/FETCH_ONLINE_VISITORS_REQUESTED')
export const FETCH_ONLINE_VISITORS_SUCCESS = Symbol('visitors/FETCH_ONLINE_VISITORS_SUCCESS')
export const FETCH_ONLINE_VISITORS_FAILED = Symbol('visitors/FETCH_ONLINE_VISITORS_FAILED')

export const VISITOR_GET_ONLINE = Symbol('visitors/VISITOR_GET_ONLINE')
export const VISITOR_GET_OFFLINE = Symbol('visitors/VISITOR_GET_OFFLINE')


